M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, June 08, 2023 at 09:11:35 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-08T21:11:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X156.209Y-96.731
X156.209Y-100.731
T2
X97.2Y-84.7
X97.2Y-113.7
X155.2Y-84.731
X155.2Y-113.7
T0
M30
